import { initializeApp } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js';
import { getDatabase, ref, get, set } from 'https://www.gstatic.com/firebasejs/10.12.2/firebase-database.js';
const firebaseConfig={apiKey:'AIzaSyAa39XCZwLiIz0xlzjEGAVUbMl5r8Y6dWQ',authDomain:'ai-class-dashboard-f0fbd.firebaseapp.com',databaseURL:'https://ai-class-dashboard-f0fbd-default-rtdb.firebaseio.com',projectId:'ai-class-dashboard-f0fbd',storageBucket:'ai-class-dashboard-f0fbd.firebasestorage.app',messagingSenderId:'1009369795925',appId:'1:1009369795925:web:c2de08f7a5c5bbc19773dc'};
const students=['UF-4602','SH-9733','NG-3471','AR-8540','IS-3124','AK-5118','YP-9838','JG-8036','DL-5638','MR-8419','MB-5198','AW-2413','SS-3900','PL-1623','SB-3139','MF-5462','AG-4344','AS-5720','ZT-4302','MG-8004','MH-4597','EB-7098','ZK-9057','DP-7669','SJ-6047','YF-9052','TE-5169','JB-5915','SS-4558','MG-3297','JK-3407','JW-9447'];
const app=initializeApp(firebaseConfig),db=getDatabase(app),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let state={sessions:{},meta:{}},dirty=false;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function toast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function blank(){const s={};for(let i=1;i<=8;i++)s[i]={title:`Class ${i}`,date:'',status:'not-started',notes:'',resources:[],attendance:{},review:{}};return{sessions:s,meta:{}}}
function normalize(){state.sessions??={};state.meta??={};for(let i=1;i<=8;i++){state.sessions[i]??={};const s=state.sessions[i];s.title??=`Class ${i}`;s.date??='';s.status??='not-started';s.notes??='';s.resources=Array.isArray(s.resources)?s.resources:[];s.attendance??={};s.review??={}}}
function markDirty(){dirty=true;$('#dirtyLabel').textContent='Unsaved changes — click Save to publish.';$('#dirtyLabel').classList.add('warning')}
function renderMatrix(){normalize();$('#matrix thead').innerHTML=`<tr><th>Student</th>${Array.from({length:8},(_,x)=>`<th>${esc(state.sessions[x+1].title||`Class ${x+1}`)}<br><small>A / R</small></th>`).join('')}</tr>`;$('#matrix tbody').innerHTML=students.map(st=>`<tr><td>${st}</td>${Array.from({length:8},(_,x)=>{const i=x+1,s=state.sessions[i];return `<td><div class="checkcell"><label title="Attended">A <input class="check" type="checkbox" data-s="${st}" data-i="${i}" data-k="attendance" ${s.attendance[st]?'checked':''}></label><label title="Reviewed">R <input class="check" type="checkbox" data-s="${st}" data-i="${i}" data-k="review" ${s.review[st]?'checked':''}></label></div></td>`}).join('')}</tr>`).join('');$$('.check').forEach(x=>x.onchange=markDirty)}
function resourceRow(i,r={}){return `<div class="resource-edit"><input class="resource-label" data-i="${i}" value="${esc(r.label||'')}" placeholder="Resource name"><input class="resource-url" data-i="${i}" value="${esc(r.url||'')}" placeholder="https://…"><button type="button" class="remove-resource" aria-label="Remove">✕</button></div>`}
function renderSessions(){normalize();$('#sessionEditors').innerHTML=Array.from({length:8},(_,x)=>{const i=x+1,s=state.sessions[i];return `<article class="session-editor" data-editor="${i}"><div class="editor-heading"><span>SESSION ${i}</span><strong>${esc(s.title)}</strong></div><div class="form-grid"><div class="field"><label>Class title</label><input data-field="title" data-i="${i}" value="${esc(s.title)}"></div><div class="field"><label>Date</label><input type="date" data-field="date" data-i="${i}" value="${esc(s.date)}"></div><div class="field"><label>Status</label><select data-field="status" data-i="${i}"><option value="not-started" ${s.status==='not-started'?'selected':''}>Not Started</option><option value="in-progress" ${s.status==='in-progress'?'selected':''}>In Progress</option><option value="completed" ${s.status==='completed'?'selected':''}>Completed</option></select></div><div class="field full"><label>Instructor notes</label><textarea data-field="notes" data-i="${i}" rows="3" placeholder="Homework, reminders, or class notes…">${esc(s.notes)}</textarea></div></div><div class="resource-editor"><div class="resource-head"><h4>Files and links</h4><button type="button" class="btn tiny add-resource" data-i="${i}">+ Add resource</button></div><div class="resource-rows">${s.resources.map(r=>resourceRow(i,r)).join('')}</div></div></article>`}).join('');$$('[data-field]').forEach(x=>x.oninput=markDirty);$$('.add-resource').forEach(b=>b.onclick=()=>{b.closest('.session-editor').querySelector('.resource-rows').insertAdjacentHTML('beforeend',resourceRow(+b.dataset.i));wireResourceButtons();markDirty()});wireResourceButtons()}
function wireResourceButtons(){$$('.remove-resource').forEach(b=>b.onclick=()=>{b.closest('.resource-edit').remove();markDirty()});$$('.resource-label,.resource-url').forEach(x=>x.oninput=markDirty)}
function renderBulkSessionOptions(){const select=$('#bulkSession');if(!select)return;const current=select.value||'1';select.innerHTML=Array.from({length:8},(_,x)=>{const i=x+1;return `<option value="${i}">Class ${i}: ${esc(state.sessions[i].title||`Class ${i}`)}</option>`}).join('');select.value=current;}
function render(){renderMatrix();renderSessions();renderBulkSessionOptions()}
async function load(){try{const snap=await get(ref(db,'trainingDashboard'));state=snap.val()||blank();normalize();render();$('#connection').textContent='● Firebase connected';$('#databaseInfo').textContent='Connected to ai-class-dashboard-f0fbd Realtime Database.';const t=state.meta?.updatedAt;$('#lastSaved').textContent=`Last saved: ${t?new Date(t).toLocaleString():'Never'}`;$('#updatedBy').value=state.meta?.updatedBy||'Admin'}catch(e){$('#connection').textContent='Connection error';$('#databaseInfo').textContent=e.message;toast(e.message)}}
function collect(){normalize();$$('[data-field]').forEach(x=>state.sessions[x.dataset.i][x.dataset.field]=x.value);$$('.check').forEach(x=>state.sessions[x.dataset.i][x.dataset.k][x.dataset.s]=x.checked);$$('.session-editor').forEach(editor=>{const i=editor.dataset.editor;state.sessions[i].resources=[...editor.querySelectorAll('.resource-edit')].map(row=>({label:row.querySelector('.resource-label').value.trim(),url:row.querySelector('.resource-url').value.trim()})).filter(r=>r.url)})}
function setClassMarks(key,val){const session=$('#bulkSession')?.value||'1';$$(`.check[data-i="${session}"][data-k="${key}"]`).forEach(x=>x.checked=val);markDirty();toast(`${val?'Marked':'Cleared'} ${key==='attendance'?'attendance':'reviews'} for ${state.sessions[session].title||`Class ${session}`}`)}
function clearSelectedClass(){const session=$('#bulkSession')?.value||'1';$$(`.check[data-i="${session}"]`).forEach(x=>x.checked=false);markDirty();toast(`Cleared all marks for ${state.sessions[session].title||`Class ${session}`}`)}
function unlock(){if($('#pin').value==='5339'){$('#login').style.display='none';sessionStorage.setItem('adminUnlocked','1');load()}else $('#loginMsg').textContent='Incorrect PIN'}
$('#unlock').onclick=unlock;$('#pin').addEventListener('keydown',e=>{if(e.key==='Enter')unlock()});if(sessionStorage.getItem('adminUnlocked')==='1'){$('#login').style.display='none';load()}
$('#lock').onclick=()=>{sessionStorage.removeItem('adminUnlocked');location.reload()};$('#allPresent').onclick=()=>setClassMarks('attendance',true);$('#allReviewed').onclick=()=>setClassMarks('review',true);$('#clearAll').onclick=()=>{const session=$('#bulkSession')?.value||'1';if(confirm(`Clear attendance and review marks for ${state.sessions[session].title||`Class ${session}`}?`))clearSelectedClass()};
$$('[data-admin-view]').forEach(btn=>btn.onclick=()=>{$$('[data-admin-view]').forEach(x=>x.classList.toggle('active',x===btn));$$('.admin-view').forEach(v=>v.classList.toggle('active',v.id===`admin-${btn.dataset.adminView}`))});
$('#save').onclick=async()=>{collect();state.meta={...state.meta,updatedAt:Date.now(),updatedBy:$('#updatedBy').value.trim()||'Admin',version:2};try{await set(ref(db,'trainingDashboard'),state);dirty=false;toast('Saved successfully');sessionStorage.removeItem('adminUnlocked');setTimeout(()=>location.reload(),900)}catch(e){toast(`Save failed: ${e.message}`)}};
$('#exportBtn').onclick=()=>{collect();const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`aimplement-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500)};
$('#importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{state=JSON.parse(await f.text());normalize();render();markDirty();toast('Backup loaded. Click Save to publish.')}catch{toast('Invalid backup file')}};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue=''}});
